import type { Metadata } from 'next'

import './globals.css'
import Navbar from './nav/Navbar'
import ToasterProvider from './providers/ToasterProvider'
import SignalrProvider from './providers/SignalrProvider'
import { GetCurrentUser } from './actions/authActions'

export const metadata: Metadata = {
  title: 'Carsties',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const user = await GetCurrentUser();

  return (
    <html lang="en">
      <body>
        <ToasterProvider />
        <Navbar />
        <main className='container mx-auto px-5 pt-10'>
          <SignalrProvider user={user}>
            {children}
          </SignalrProvider>
        </main>

      </body>
    </html>
  )
}
